### ISSUE TITLE
About Step2

### ISSUE THREAD

**Issue by Fulin-Gao** [OatmealLiu/class-iNCD#10]
In the second step, do we need to perform classification or clustering on the 10 tinyimagenet classes from the first step?

**Comment by OatmealLiu** [comment]
Hi,

During testing, for the novel splits, clustering accuracy is used as evaluation metrics. During training, clustering and classification, essentially, is the same, because the loss is computed between the label (you can also say it's cluster ID) assigned to the sample and the "GT label" or "Generated Pseudo label".

Best regards,
Mingxuan
